---
name: Yamllint

on:
  push:
    branches:
      - master
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
